Add favicon
digitalbazaar/canivc pull request #26
Opened 2024-03-19 17:35 UTC by jameseaster

#### _Resolves - add favicon_

---

### What kind of change does this PR introduce?

- Style update.

<br/>

### What is the current behavior?

- No favicon.

<br/>

### What is the new behavior?

- Favicon with the initials VC.

<br/>

### Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

<br/>

### How has this been tested?

- Locally rendered.

<br/>

### Screenshots:
> Favicon
> 
> <img  alt="favicon" width="300" src="https://github.com/digitalbazaar/canivc/assets/56396286/21858f51-6258-4c19-ab23-de610e26bac6" />

2024-03-19 17:40 UTC, BigBlueHat requested changes
We may as well name the site in the manifest, so if someone "installs" it, it gets a name.

2024-03-19 20:46 UTC, davidlehn reviewed
- The white on light blue contrast makes it more difficult to read at small sizes, especially with the light upper left fade.
- Is the source file for these easy to put in source control too?

2024-03-19 20:46 UTC, davidlehn commented on images/favicon/site.webmanifest
- This is a strange source location for this file.
- Would be easier to read if indented.

2024-03-19 20:46 UTC, davidlehn commented on .eleventy.js
> +
```suggestion

```

2024-03-21 16:54 UTC, jameseaster commented on images/favicon/site.webmanifest
Updated to be indented like normal JSON: aea6397

2024-03-21 16:55 UTC, jameseaster commented on images/favicon/site.webmanifest
@BigBlueHat Any thoughts on better placement for the web.manifest file? It's directly correlated with the favicon which is why they are grouped together here (not saying that's the best solution, just the current reasoning).

2024-04-04 14:03 UTC, BigBlueHat commented on images/favicon/site.webmanifest
I'd put `site.webmanifest` at the root of the site and fix the paths. I know the way we're using it is favicon focused, but it's technically "about" the whole site, so putting it at the root makes the most sense to me (and is pretty typical).

2024-04-04 14:05 UTC, BigBlueHat commented
> * The white on light blue contrast makes it more difficult to read at small sizes, especially with the light upper left fade.

I agree the contrast is probably not strong enough when it's shrunk down super tiny. @jameseaster maybe push the gradient a bit so there's more blue than white?

2024-04-10 16:52 UTC, jameseaster commented on images/favicon/site.webmanifest
@BigBlueHat @davidlehn

Update: site.webmanifest is now at the root level and the favicon is a solid blue color that matches canivc's primary theme color. 3ab3530

2024-04-10 18:09 UTC, davidlehn commented on site.webmanifest
Need an .eleventy.js rule to copy this.

2024-04-10 18:38 UTC, jameseaster commented on site.webmanifest
Totally, good catch, thanks!

2024-04-10 20:09 UTC, davidlehn approved these changes

2024-04-11 15:23 UTC, BigBlueHat approved these changes

2024-04-11 15:23 UTC, merged